import React, { useCallback, useEffect, useMemo, useState } from 'react';
import {
  ActivityIndicator, Alert, FlatList, Image, Modal, Pressable, SafeAreaView, ScrollView,
  StatusBar, StyleSheet, Text, TextInput, View,
} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as ImagePicker from 'expo-image-picker';
import AccountBottomSheet from './src/components/AccountBottomSheet';
import AuthModal from './src/components/AuthModal';
import { COLORS } from './src/constants/theme';
import { apiClient, authStorage, toAbsoluteUrl } from './src/services/api';

const TABS = [
  { key: 'home', icon: '⌂', label: 'Trang chủ' }, { key: 'explore', icon: '⌘', label: 'Khám phá' },
  { key: 'library', icon: '▤', label: 'Thư viện' }, { key: 'ranking', icon: '♛', label: 'Xếp hạng' }, { key: 'profile', icon: '◉', label: 'Tài khoản' },
];
const READING_PROGRESS_KEY = '@mangadex/reading-progress';
const READER_MODE_KEY = '@mangadex/reader-mode';
const compact = (value = 0) => { const n = Number(value) || 0; return n >= 1e6 ? `${(n / 1e6).toFixed(1)}M` : n >= 1e3 ? `${(n / 1e3).toFixed(1)}K` : String(n); };
const unpack = (response) => response?.data?.success ? response.data.data : response?.data;
const errorMessage = (error, fallback = 'Không thể kết nối máy chủ. Vui lòng thử lại.') => error?.response?.data?.message || error?.response?.data?.error || fallback;
const tags = (story) => {
  const raw = story?.categories || story?.category_names || '';
  const value = Array.isArray(raw) ? raw : raw.split(',').map((item) => item.trim()).filter(Boolean);
  return value.slice(0, 2);
};
const nameFor = (user) => user?.full_name || user?.username || 'Khách';
const initials = (user) => nameFor(user).trim().slice(0, 2).toUpperCase();

function Avatar({ user, style, textStyle }) {
  return <View style={[styles.avatar, style]}>{user?.avatar_url ? <Image source={{ uri: toAbsoluteUrl(user.avatar_url) }} style={styles.avatarImage} /> : <Text style={[styles.avatarText, textStyle]}>{initials(user)}</Text>}</View>;
}

function Header({ user, onAvatar, onSearch, onSettings }) {
  return <View style={styles.header}><View><Text style={styles.logo}>Manga<Text style={styles.logoAccent}>Dex</Text></Text><Text style={styles.greeting}>Thế giới truyện của bạn</Text></View><View style={styles.headerActions}>
    <Pressable accessibilityLabel="Tìm kiếm" onPress={onSearch} style={styles.headerIcon}><Text>⌕</Text></Pressable>
    <Pressable accessibilityLabel="Cài đặt đọc" onPress={onSettings} style={styles.headerIcon}><Text>⚙</Text></Pressable>
    <Pressable accessibilityLabel="Tài khoản" onPress={onAvatar}><Avatar user={user} style={styles.headerAvatar} textStyle={styles.headerAvatarText} /></Pressable>
  </View></View>;
}

function StoryCard({ story, onPress }) {
  return <Pressable style={styles.storyCard} onPress={() => onPress(story)}><View style={styles.coverWrap}>
    <Image source={{ uri: toAbsoluteUrl(story.cover_image) }} style={styles.cover} /><View style={styles.coverShade} />
    <View style={styles.metrics}><Text style={styles.metric}>♡ {compact(story.total_likes)}</Text><Text style={styles.metric}>◉ {compact(story.views)}</Text></View>
    <View style={styles.tagRow}>{tags(story).map((tag) => <View key={tag} style={styles.tag}><Text style={styles.tagText}>{tag}</Text></View>)}</View>
  </View><Text numberOfLines={2} style={styles.storyTitle}>{story.title}</Text><Text numberOfLines={1} style={styles.storyAuthor}>{story.author_name || 'Đang cập nhật'}</Text></Pressable>;
}

function HomeScreen({ stories, loading, user, onOpenStory, onAvatar, onSearch, onSettings }) {
  return <FlatList data={stories} keyExtractor={(item) => String(item.id)} numColumns={2} contentContainerStyle={styles.homeList} columnWrapperStyle={styles.gridRow}
    ListHeaderComponent={<><Header user={user} onAvatar={onAvatar} onSearch={onSearch} onSettings={onSettings} /><View style={styles.sectionHeader}><View><Text style={styles.eyebrow}>KHÁM PHÁ</Text><Text style={styles.heading}>Dành cho bạn</Text></View><Text style={styles.seeAll}>{stories.length} truyện</Text></View>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.quickList}>{stories.slice(0, 6).map((story) => <Pressable key={story.id} style={styles.quickItem} onPress={() => onOpenStory(story)}><View style={styles.quickRing}><Image source={{ uri: toAbsoluteUrl(story.cover_image) }} style={styles.quickCover} /></View><Text numberOfLines={1} style={styles.quickName}>{story.title}</Text></Pressable>)}</ScrollView>
      <View style={[styles.sectionHeader, styles.latestHeader]}><View><Text style={styles.eyebrow}>CẬP NHẬT</Text><Text style={styles.heading}>Mới nhất</Text></View></View></>}
    renderItem={({ item }) => <StoryCard story={item} onPress={onOpenStory} />}
    ListEmptyComponent={<Empty loading={loading} text="Chưa có truyện được tải từ máy chủ." />}
  />;
}

function SearchScreen({ onBack, onOpenStory }) {
  const [query, setQuery] = useState(''); const [results, setResults] = useState([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  useEffect(() => { const keyword = query.trim(); if (!keyword) { setResults([]); setError(''); return undefined; } let active = true; const timer = setTimeout(async () => { setLoading(true); try { const data = unpack(await apiClient.getStories({ search: keyword, limit: 20, sort: 'latest' })); if (active) setResults(data?.data || []); } catch (e) { if (active) setError(errorMessage(e)); } finally { if (active) setLoading(false); } }, 300); return () => { active = false; clearTimeout(timer); }; }, [query]);
  return <View style={styles.searchPage}><View style={styles.searchTop}><Pressable onPress={onBack} style={styles.searchBack}><Text style={styles.backText}>‹</Text></Pressable><Text style={styles.searchTitle}>Tìm kiếm</Text></View><View style={styles.searchBox}><Text style={styles.searchGlyph}>⌕</Text><TextInput autoFocus value={query} onChangeText={setQuery} placeholder="Tên truyện, tên khác..." placeholderTextColor={COLORS.textMuted} style={styles.searchInput} /><Pressable onPress={() => setQuery('')}><Text style={styles.clearSearch}>{query ? '×' : ''}</Text></Pressable></View>
    {loading ? <ActivityIndicator color={COLORS.primary} style={styles.searchState} /> : null}{error ? <Text style={styles.errorText}>{error}</Text> : null}{!loading && query && !error && !results.length ? <Text style={styles.emptyText}>Không tìm thấy truyện phù hợp.</Text> : null}
    <FlatList data={results} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.searchResults} renderItem={({ item }) => <Pressable style={styles.searchResult} onPress={() => onOpenStory(item)}><Image source={{ uri: toAbsoluteUrl(item.cover_image) }} style={styles.searchCover} /><View style={styles.searchCopy}><Text numberOfLines={2} style={styles.searchStoryTitle}>{item.title}</Text><Text style={styles.storyAuthor}>{item.author_name || 'Đang cập nhật'}</Text><Text style={styles.searchChapter}>Chương mới nhất: {item.latest_chapter || '—'}</Text></View><Text style={styles.chevron}>›</Text></Pressable>} />
  </View>;
}

function ExploreScreen({ categories, onOpenCategory }) {
  const groups = useMemo(() => categories.reduce((result, category) => { const letter = /^[A-Z]/i.test(category.name) ? category.name[0].toUpperCase() : '#'; (result[letter] ||= []).push(category); return result; }, {}), [categories]);
  return <ScrollView contentContainerStyle={styles.pageContent}><Text style={styles.eyebrow}>DANH MỤC</Text><Text style={styles.pageTitle}>Khám phá truyện</Text><Text style={styles.pageIntro}>Số lượng truyện được lấy trực tiếp từ dữ liệu hệ thống.</Text>{Object.keys(groups).sort().map((letter) => <View key={letter} style={styles.categorySection}><Text style={styles.letter}>{letter}</Text>{groups[letter].map((category, index) => <Pressable key={category.id} style={styles.categoryCard} onPress={() => onOpenCategory(category)}><Text style={styles.categoryNumber}>{String(index + 1).padStart(2, '0')}</Text><Text style={styles.categoryName}>{category.name}</Text><Text style={styles.categoryCount}>{category.story_count || 0} truyện</Text><Text style={styles.chevron}>›</Text></Pressable>)}</View>)}{!categories.length ? <Empty text="Chưa có thể loại nào." /> : null}</ScrollView>;
}

function LibraryScreen({ user, history, follows, onOpenHistory, onOpenStory, onAuthenticate }) {
  const [tab, setTab] = useState('history');
  if (!user) return <GuestNotice title="Tủ truyện của bạn" text="Đăng nhập để xem truyện đang đọc và truyện đã theo dõi." onPress={onAuthenticate} />;
  const items = tab === 'history' ? history : follows;
  return <ScrollView contentContainerStyle={styles.pageContent}><Text style={styles.eyebrow}>BỘ SƯU TẬP</Text><Text style={styles.pageTitle}>Thư viện của tôi</Text><View style={styles.pills}><Pressable onPress={() => setTab('history')} style={[styles.pill, tab === 'history' && styles.pillActive]}><Text style={[styles.pillText, tab === 'history' && styles.pillTextActive]}>Đọc tiếp ({history.length})</Text></Pressable><Pressable onPress={() => setTab('follows')} style={[styles.pill, tab === 'follows' && styles.pillActive]}><Text style={[styles.pillText, tab === 'follows' && styles.pillTextActive]}>Theo dõi ({follows.length})</Text></Pressable></View>
    {!items.length ? <Empty text={tab === 'history' ? 'Bạn chưa đọc chương nào.' : 'Bạn chưa theo dõi truyện nào.'} /> : items.map((item) => { const story = tab === 'history' ? { id: item.story_id, title: item.story_title, slug: item.story_slug, cover_image: item.cover_image } : item; const chapter = tab === 'history' ? { id: item.chapter_id, chapter_number: item.chapter_number, title: item.chapter_title } : null; const progress = chapter ? Math.min(100, Math.round((Number(item.chapter_number) / Math.max(1, Number(item.total_chapters))) * 100)) : 0; return <Pressable key={`${tab}-${story.id}`} style={styles.libraryItem} onPress={() => chapter ? onOpenHistory(story, chapter) : onOpenStory(story)}><Image source={{ uri: toAbsoluteUrl(story.cover_image) }} style={styles.libraryCover} /><View style={styles.libraryInfo}><Text style={styles.libraryStory}>{story.title}</Text><Text style={styles.storyAuthor}>{chapter ? `${chapter.title || `Chương ${chapter.chapter_number}`} · ${progress}%` : `Mới nhất: Chương ${item.latest_chapter || '—'}`}</Text>{chapter ? <View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${progress}%` }]} /></View> : null}</View><Text style={styles.chevron}>›</Text></Pressable>; })}
  </ScrollView>;
}

function RankingScreen({ stories, onOpenStory }) { return <ScrollView contentContainerStyle={styles.pageContent}><Text style={styles.eyebrow}>BẢNG XẾP HẠNG</Text><Text style={styles.pageTitle}>Được xem nhiều nhất</Text>{stories.slice(0, 10).map((story, index) => <Pressable key={story.id} style={styles.rankItem} onPress={() => onOpenStory(story)}><Text style={[styles.rankNumber, index < 3 && styles.rankNumberHot]}>{String(index + 1).padStart(2, '0')}</Text><Image source={{ uri: toAbsoluteUrl(story.cover_image) }} style={styles.rankCover} /><View style={styles.rankInfo}><Text numberOfLines={1} style={styles.rankTitle}>{story.title}</Text><Text style={styles.storyAuthor}>{story.author_name || 'Đang cập nhật'}</Text><Text style={styles.rankViews}>◉ {compact(story.views)} lượt xem</Text></View></Pressable>)}</ScrollView>; }

function ProfileScreen({ user, stats, onAvatar, onAuthenticate }) {
  if (!user) return <GuestNotice title="Tài khoản" text="Đăng nhập để lưu Tủ truyện, yêu thích và bình luận." onPress={onAuthenticate} />;
  return <ScrollView contentContainerStyle={styles.pageContent}><View style={styles.profileHero}><Avatar user={user} style={styles.profileAvatar} textStyle={styles.profileAvatarText} /><Text style={styles.profileName}>{nameFor(user)}</Text><Text style={styles.profileEmail}>{user.email}</Text><Pressable style={styles.profileButton} onPress={onAvatar}><Text style={styles.profileButtonText}>Mở cài đặt tài khoản</Text></Pressable></View><Text style={styles.subheading}>Hoạt động của bạn</Text><View style={styles.statRow}>{[[stats.follows, 'Đã theo dõi'], [stats.likes, 'Đã thích'], [stats.history, 'Đã đọc']].map(([value, label]) => <View key={label} style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>)}</View></ScrollView>;
}

function StoryDetail({ story, user, onBack, onRead, onRequireAuth, onUserDataChanged }) {
  const [chapters, setChapters] = useState([]); const [comments, setComments] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [followed, setFollowed] = useState(false); const [liked, setLiked] = useState(false); const [commentText, setCommentText] = useState(''); const [sending, setSending] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [chapterResult, commentResult] = await Promise.all([apiClient.getChapters(story.id), apiClient.getComments(story.id)]); setChapters(Array.isArray(unpack(chapterResult)) ? unpack(chapterResult) : []); setComments(Array.isArray(unpack(commentResult)) ? unpack(commentResult) : []); if (user) { const [followResult, likeResult] = await Promise.all([apiClient.checkFollow(story.id), apiClient.checkLike(story.id)]); setFollowed(Boolean(unpack(followResult)?.followed)); setLiked(Boolean(unpack(likeResult)?.liked)); } else { setFollowed(false); setLiked(false); } } catch (e) { setError(errorMessage(e, 'Không thể tải chi tiết truyện.')); } finally { setLoading(false); } }, [story.id, user]);
  useEffect(() => { load(); }, [load]);
  const toggle = async (kind) => { if (!user) return onRequireAuth(); try { const data = unpack(kind === 'follow' ? await apiClient.toggleFollow(story.id) : await apiClient.toggleLike(story.id)); if (kind === 'follow') setFollowed(Boolean(data?.followed)); else setLiked(Boolean(data?.liked)); onUserDataChanged(); } catch (e) { Alert.alert('Không thể cập nhật', errorMessage(e)); } };
  const sendComment = async () => { if (!user) return onRequireAuth(); if (!commentText.trim()) return; setSending(true); try { const data = unpack(await apiClient.createComment(story.id, commentText.trim())); setComments((current) => [data?.comment, ...current].filter(Boolean)); setCommentText(''); } catch (e) { Alert.alert('Không thể gửi bình luận', errorMessage(e)); } finally { setSending(false); } };
  return <ScrollView style={styles.detail} contentContainerStyle={styles.detailContent}><Pressable style={styles.backButton} onPress={onBack}><Text style={styles.backText}>‹</Text><Text style={styles.backLabel}>Quay lại</Text></Pressable><View style={styles.detailHero}><Image source={{ uri: toAbsoluteUrl(story.cover_image) }} style={styles.detailCover} /><View style={styles.detailInfo}><Text style={styles.detailTitle}>{story.title}</Text><Text style={styles.detailAuthor}>✎ {story.author_name || 'Đang cập nhật'}</Text><Text style={styles.detailStats}>◉ {compact(story.views)} · ♡ {compact(story.total_likes)}</Text><View style={styles.detailTags}>{tags(story).map((tag) => <View key={tag} style={styles.tag}><Text style={styles.tagText}>{tag}</Text></View>)}</View></View></View>
    <View style={styles.actionRow}><Pressable style={styles.readButton} onPress={() => chapters[0] && onRead(chapters[0])} disabled={loading || !chapters.length}><Text style={styles.readButtonText}>{loading ? 'Đang tải…' : '▶ Đọc từ đầu'}</Text></Pressable><Pressable onPress={() => toggle('follow')} style={[styles.secondaryButton, followed && styles.activeButton]}><Text style={styles.secondaryButtonText}>{followed ? '★ Đang theo dõi' : '☆ Theo dõi'}</Text></Pressable><Pressable onPress={() => toggle('like')} style={[styles.iconAction, liked && styles.activeButton]}><Text>{liked ? '♥' : '♡'}</Text></Pressable></View>
    <Text style={styles.subheading}>Giới thiệu</Text><Text style={styles.description}>{story.description || 'Chưa có giới thiệu cho truyện này.'}</Text><Text style={styles.subheading}>Danh sách chương</Text>{loading ? <ActivityIndicator color={COLORS.primary} /> : null}{error ? <Text style={styles.errorText}>{error}</Text> : null}{!loading && !chapters.length ? <Text style={styles.emptyText}>Truyện này chưa có chương được đăng.</Text> : null}{chapters.map((chapter) => <Pressable key={chapter.id} onPress={() => onRead(chapter)} style={styles.chapter}><View><Text style={styles.chapterTitle}>{chapter.title || `Chương ${chapter.chapter_number}`}</Text><Text style={styles.chapterDate}>◉ {compact(chapter.views)} lượt xem</Text></View><Text style={styles.chevron}>›</Text></Pressable>)}
    <Text style={styles.subheading}>Bình luận ({comments.length})</Text><View style={styles.commentForm}><TextInput value={commentText} onChangeText={setCommentText} editable={!sending} multiline placeholder={user ? 'Viết bình luận của bạn…' : 'Đăng nhập để bình luận'} placeholderTextColor={COLORS.textMuted} style={styles.commentInput} /><Pressable onPress={sendComment} disabled={sending} style={[styles.commentSend, sending && styles.disabled]}><Text style={styles.commentSendText}>{sending ? '…' : 'Gửi'}</Text></Pressable></View>{comments.length ? comments.map((comment) => <View key={comment.id} style={styles.comment}><Avatar user={comment} style={styles.commentAvatar} /><View style={styles.commentBody}><Text style={styles.commentUser}>{comment.username || 'Độc giả'}</Text><Text style={styles.commentContent}>{comment.content}</Text><Text style={styles.commentDate}>{comment.chapter_number ? `Chương ${comment.chapter_number} · ` : ''}{new Date(comment.created_at).toLocaleDateString('vi-VN')}</Text></View></View>) : <Text style={styles.emptyText}>Chưa có bình luận. Hãy là người đầu tiên chia sẻ cảm nhận.</Text>}</ScrollView>;
}

function Reader({ story, firstChapter, user, readerMode, onBack, onHistorySaved }) {
  const [chapter, setChapter] = useState(firstChapter); const [chapters, setChapters] = useState([]); const [pages, setPages] = useState([]); const [loading, setLoading] = useState(true); const [toolsVisible, setToolsVisible] = useState(true); const [chapterSheet, setChapterSheet] = useState(false);
  useEffect(() => { apiClient.getChapters(story.id).then((response) => setChapters(Array.isArray(unpack(response)) ? unpack(response) : [])).catch(() => setChapters([])); }, [story.id]);
  useEffect(() => { let active = true; setLoading(true); apiClient.getChapterImages(chapter.id).then((response) => { if (active) setPages((Array.isArray(unpack(response)) ? unpack(response) : []).sort((a, b) => (a.order_index || 0) - (b.order_index || 0))); }).catch(() => active && setPages([])).finally(() => active && setLoading(false)); apiClient.incrementChapterViews(chapter.id).catch(() => {}); const progress = { story_id: story.id, chapter_id: chapter.id, updated_at: new Date().toISOString() }; AsyncStorage.setItem(READING_PROGRESS_KEY, JSON.stringify(progress)).catch(() => {}); if (user) apiClient.saveHistory(story.id, chapter.id).then(onHistorySaved).catch(() => {}); return () => { active = false; }; }, [chapter.id, story.id, user, onHistorySaved]);
  const currentIndex = chapters.findIndex((item) => String(item.id) === String(chapter.id)); const previous = currentIndex > 0 ? chapters[currentIndex - 1] : null; const next = currentIndex >= 0 && currentIndex < chapters.length - 1 ? chapters[currentIndex + 1] : null;
  return <View style={styles.reader}>{toolsVisible && <View style={styles.readerHeader}><Pressable onPress={onBack} style={styles.readerBack}><Text style={styles.readerHeaderText}>‹</Text></Pressable><View style={styles.readerHeading}><Text numberOfLines={1} style={styles.readerTitle}>{story.title}</Text><Text style={styles.readerChapter}>{chapter.title || `Chương ${chapter.chapter_number}`} · {readerMode === 'page' ? 'Lật trang' : 'Cuộn dọc'}</Text></View><Text style={styles.readerHeaderText}>⋮</Text></View>}<ScrollView onTouchEnd={() => setToolsVisible((visible) => !visible)} contentContainerStyle={styles.readerPages}>{loading ? <ActivityIndicator color={COLORS.primary} size="large" style={styles.readerLoading} /> : null}{!loading && !pages.length ? <Text style={styles.readerEmpty}>Chương này chưa có ảnh để đọc.</Text> : null}{pages.map((page, index) => <View key={page.id || page.image_url || index} style={styles.readerPage}><Image source={{ uri: toAbsoluteUrl(page.image_url) }} style={styles.readerImage} resizeMode="contain" /><Text style={styles.readerPageNumber}>{index + 1} / {pages.length}</Text></View>)}</ScrollView>{toolsVisible && <View style={styles.readerFooter}><Pressable disabled={!previous} onPress={() => previous && setChapter(previous)} style={!previous && styles.readerDisabled}><Text style={styles.readerFooterText}>‹ Chương trước</Text></Pressable><Pressable onPress={() => setChapterSheet(true)}><Text style={styles.readerFooterText}>Danh sách chương</Text></Pressable><Pressable disabled={!next} onPress={() => next && setChapter(next)} style={!next && styles.readerDisabled}><Text style={styles.readerFooterText}>Chương sau ›</Text></Pressable></View>}<Modal transparent visible={chapterSheet} animationType="slide" onRequestClose={() => setChapterSheet(false)}><View style={styles.sheetOverlay}><Pressable style={StyleSheet.absoluteFill} onPress={() => setChapterSheet(false)} /><View style={styles.chapterSheet}><Text style={styles.sheetTitle}>Danh sách chương</Text><ScrollView>{chapters.map((item) => <Pressable key={item.id} onPress={() => { setChapter(item); setChapterSheet(false); }} style={[styles.sheetChapter, item.id === chapter.id && styles.sheetChapterActive]}><Text style={styles.sheetChapterText}>{item.title || `Chương ${item.chapter_number}`}</Text></Pressable>)}</ScrollView></View></View></Modal></View>;
}

function SettingsModal({ mode, visible, user, readerMode, onClose, onSaveProfile, onUploadAvatar, onChangePassword, onReaderMode }) {
  const [fullName, setFullName] = useState(user?.full_name || ''); const [gender, setGender] = useState(user?.gender || ''); const [avatarAsset, setAvatarAsset] = useState(null); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { setFullName(user?.full_name || ''); setGender(user?.gender || ''); setAvatarAsset(null); setError(''); }, [user, mode, visible]);
  const chooseAvatar = async () => {
    setError('');
    const permission = await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (!permission.granted) { setError('Cần quyền truy cập thư viện ảnh để chọn ảnh đại diện.'); return; }
    const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: true, aspect: [1, 1], quality: 0.8 });
    if (!result.canceled) {
      const asset = result.assets[0];
      const acceptedTypes = new Set(['image/jpeg', 'image/png', 'image/webp', 'image/gif']);
      if (asset.fileSize && asset.fileSize > 5 * 1024 * 1024) { setError('Ảnh đại diện có dung lượng tối đa 5MB.'); return; }
      if (asset.mimeType && !acceptedTypes.has(asset.mimeType)) { setError('Chỉ hỗ trợ ảnh JPG, PNG, WEBP hoặc GIF.'); return; }
      setAvatarAsset(asset);
    }
  };
  const save = async () => { setSaving(true); setError(''); try { if (mode === 'profile') { const uploadedPath = avatarAsset ? await onUploadAvatar(avatarAsset) : user?.avatar_url; await onSaveProfile({ full_name: fullName, gender, avatar_url: uploadedPath }); } if (mode === 'security') await onChangePassword(currentPassword, newPassword); onClose(); } catch (e) { setError(errorMessage(e)); } finally { setSaving(false); } };
  const body = mode === 'reader' ? <><Text style={styles.modalDescription}>Chọn cách hiển thị phù hợp với bạn.</Text>{[['scroll', 'Cuộn dọc vô tận (Webtoon)'], ['page', 'Lật từng trang']].map(([value, label]) => <Pressable key={value} onPress={() => { onReaderMode(value); onClose(); }} style={[styles.settingChoice, readerMode === value && styles.settingChoiceActive]}><Text style={styles.settingChoiceText}>{readerMode === value ? '✓ ' : ''}{label}</Text></Pressable>)}</> : mode === 'profile' ? <><Pressable onPress={chooseAvatar} style={styles.avatarPicker}><Image source={{ uri: avatarAsset?.uri || toAbsoluteUrl(user?.avatar_url) }} style={styles.avatarPickerImage} /><View><Text style={styles.avatarPickerTitle}>Chọn ảnh từ thư viện</Text><Text style={styles.avatarPickerHint}>JPG, PNG, WEBP hoặc GIF · tối đa 5MB</Text></View></Pressable><TextInput value={fullName} onChangeText={setFullName} placeholder="Họ và tên" placeholderTextColor={COLORS.textMuted} style={styles.modalInput} /><TextInput value={gender} onChangeText={setGender} placeholder="Giới tính: male, female hoặc other" placeholderTextColor={COLORS.textMuted} style={styles.modalInput} /></> : mode === 'security' ? <><TextInput value={currentPassword} onChangeText={setCurrentPassword} secureTextEntry placeholder="Mật khẩu hiện tại" placeholderTextColor={COLORS.textMuted} style={styles.modalInput} /><TextInput value={newPassword} onChangeText={setNewPassword} secureTextEntry placeholder="Mật khẩu mới (ít nhất 6 ký tự)" placeholderTextColor={COLORS.textMuted} style={styles.modalInput} /></> : <Text style={styles.modalDescription}>{mode === 'Thông báo' ? 'MangaDex Mobile v1.0.0 sẽ thông báo khi truyện bạn theo dõi có chương mới.' : 'MangaDex Mobile v1.0.0: đăng nhập, theo dõi truyện, lưu tiến độ và bình luận ngay trong ứng dụng.'}</Text>;
  const title = mode === 'reader' ? 'Cài đặt đọc' : mode === 'profile' ? 'Chỉnh sửa hồ sơ' : mode === 'security' ? 'Bảo mật' : mode;
  return <Modal transparent visible={visible} animationType="fade" onRequestClose={onClose}><View style={styles.modalOverlay}><Pressable style={StyleSheet.absoluteFill} onPress={onClose} /><View style={styles.settingsCard}><Text style={styles.settingsTitle}>{title}</Text>{body}{error ? <Text style={styles.errorText}>{error}</Text> : null}{['profile', 'security'].includes(mode) ? <Pressable disabled={saving} onPress={save} style={[styles.modalSave, saving && styles.disabled]}>{saving ? <ActivityIndicator color="#FFF" /> : <Text style={styles.modalSaveText}>Lưu thay đổi</Text>}</Pressable> : null}<Pressable onPress={onClose} style={styles.modalCancel}><Text style={styles.modalCancelText}>Đóng</Text></Pressable></View></View></Modal>;
}

function GuestNotice({ title, text, onPress }) { return <View style={styles.guestPage}><Text style={styles.eyebrow}>TÀI KHOẢN</Text><Text style={styles.pageTitle}>{title}</Text><Text style={styles.pageIntro}>{text}</Text><Pressable onPress={onPress} style={styles.guestButton}><Text style={styles.readButtonText}>Đăng nhập / Đăng ký</Text></Pressable></View>; }
function Empty({ text, loading }) { return <View style={styles.empty}><>{loading ? <ActivityIndicator color={COLORS.primary} /> : null}<Text style={styles.emptyText}>{text}</Text></></View>; }
function BottomTabs({ active, onChange }) { return <View style={styles.tabBar}>{TABS.map((tab) => <Pressable key={tab.key} onPress={() => onChange(tab.key)} style={[styles.tab, tab.key === 'library' && styles.centerTabSlot]}>{tab.key === 'library' ? <View style={[styles.centerButton, active === tab.key && styles.centerButtonActive]}><Text style={styles.centerIcon}>▤</Text></View> : <><Text style={[styles.tabIcon, active === tab.key && styles.tabActive]}>{tab.icon}</Text><Text style={[styles.tabLabel, active === tab.key && styles.tabLabelActive]}>{tab.label}</Text></>}{tab.key === 'library' && <Text style={[styles.tabLabel, styles.centerLabel, active === tab.key && styles.tabLabelActive]}>Thư viện</Text>}</Pressable>)}</View>; }

export default function App() {
  const [activeTab, setActiveTab] = useState('home'); const [stories, setStories] = useState([]); const [categories, setCategories] = useState([]); const [loading, setLoading] = useState(true); const [user, setUser] = useState(null); const [history, setHistory] = useState([]); const [follows, setFollows] = useState([]); const [likes, setLikes] = useState([]); const [sheetVisible, setSheetVisible] = useState(false); const [authVisible, setAuthVisible] = useState(false); const [searchVisible, setSearchVisible] = useState(false); const [selectedStory, setSelectedStory] = useState(null); const [readingSession, setReadingSession] = useState(null); const [settingMode, setSettingMode] = useState(null); const [readerMode, setReaderMode] = useState('scroll');
  const loadPersonal = useCallback(async () => { try { const [h, f, l] = await Promise.all([apiClient.getHistory(), apiClient.getFollows(), apiClient.getLikes()]); setHistory(Array.isArray(unpack(h)) ? unpack(h) : []); setFollows(Array.isArray(unpack(f)) ? unpack(f) : []); setLikes(Array.isArray(unpack(l)) ? unpack(l) : []); } catch { setHistory([]); setFollows([]); setLikes([]); } }, []);
  const loadCatalog = useCallback(async () => { setLoading(true); try { const [storyResult, categoryResult] = await Promise.all([apiClient.getStories({ limit: 50, sort: 'latest' }), apiClient.getCategories()]); const storyData = unpack(storyResult); const categoryData = unpack(categoryResult); setStories(Array.isArray(storyData?.data) ? storyData.data : []); setCategories(Array.isArray(categoryData) ? categoryData : []); } catch { setStories([]); setCategories([]); } finally { setLoading(false); } }, []);
  useEffect(() => { loadCatalog(); AsyncStorage.getItem(READER_MODE_KEY).then((value) => value && setReaderMode(value)); authStorage.getToken().then(async (token) => { if (!token) return; try { const data = unpack(await apiClient.getMe(token)); setUser(data?.user || null); await loadPersonal(); } catch { await authStorage.clearToken(); } }); }, [loadCatalog, loadPersonal]);
  useEffect(() => { if (user) loadPersonal(); }, [activeTab, user, loadPersonal]);
  const authenticate = async (token, fallbackUser) => { await authStorage.saveToken(token); try { const data = unpack(await apiClient.getMe(token)); setUser(data?.user || fallbackUser); } catch { setUser(fallbackUser); } await loadPersonal(); };
  const logout = async () => { await authStorage.clearToken(); setUser(null); setHistory([]); setFollows([]); setLikes([]); setSheetVisible(false); setActiveTab('home'); };
  const openCategory = async (category) => { setActiveTab('home'); setLoading(true); try { const data = unpack(await apiClient.getStories({ include_cats: category.slug, limit: 50, sort: 'latest' })); setStories(Array.isArray(data?.data) ? data.data : []); } catch (e) { Alert.alert('Không thể tải thể loại', errorMessage(e)); } finally { setLoading(false); } };
  const openSetting = (action) => { setSheetVisible(false); const mapping = { 'Cài đặt đọc': 'reader', 'Chỉnh sửa hồ sơ': 'profile', 'Bảo mật': 'security' }; if (action === 'logout') return logout(); if (['profile', 'security'].includes(mapping[action]) && !user) return setAuthVisible(true); setSettingMode(mapping[action] || action); };
  const saveProfile = async (payload) => { const data = unpack(await apiClient.updateProfile(payload)); setUser(data?.user || user); };
  const uploadAvatar = async (asset) => { const data = unpack(await apiClient.uploadAvatar(asset)); return data?.avatar_url; };
  const changePassword = (current, next) => apiClient.changePassword(current, next);
  const chooseReaderMode = async (value) => { setReaderMode(value); await AsyncStorage.setItem(READER_MODE_KEY, value); };
  if (readingSession) return <Reader story={readingSession.story} firstChapter={readingSession.chapter} user={user} readerMode={readerMode} onBack={() => setReadingSession(null)} onHistorySaved={loadPersonal} />;
  const openStory = (story) => { setSearchVisible(false); setSelectedStory(story); };
  if (selectedStory) return <SafeAreaView style={styles.app}><StatusBar barStyle="light-content" /><StoryDetail story={selectedStory} user={user} onBack={() => setSelectedStory(null)} onRead={(chapter) => setReadingSession({ story: selectedStory, chapter })} onRequireAuth={() => setAuthVisible(true)} onUserDataChanged={loadPersonal} /><AuthModal visible={authVisible} onClose={() => setAuthVisible(false)} onAuthenticated={authenticate} /></SafeAreaView>;
  if (searchVisible) return <SafeAreaView style={styles.app}><StatusBar barStyle="light-content" /><SearchScreen onBack={() => setSearchVisible(false)} onOpenStory={openStory} /></SafeAreaView>;
  const screens = { home: <HomeScreen stories={stories} loading={loading} user={user} onOpenStory={openStory} onAvatar={() => setSheetVisible(true)} onSearch={() => setSearchVisible(true)} onSettings={() => setSettingMode('reader')} />, explore: <ExploreScreen categories={categories} onOpenCategory={openCategory} />, library: <LibraryScreen user={user} history={history} follows={follows} onOpenHistory={(story, chapter) => setReadingSession({ story, chapter })} onOpenStory={openStory} onAuthenticate={() => setAuthVisible(true)} />, ranking: <RankingScreen stories={[...stories].sort((a, b) => (b.views || 0) - (a.views || 0))} onOpenStory={openStory} />, profile: <ProfileScreen user={user} stats={{ follows: follows.length, likes: likes.length, history: history.length }} onAvatar={() => setSheetVisible(true)} onAuthenticate={() => setAuthVisible(true)} /> };
  return <SafeAreaView style={styles.app}><StatusBar barStyle="light-content" backgroundColor={COLORS.background} />{screens[activeTab]}<BottomTabs active={activeTab} onChange={setActiveTab} /><AccountBottomSheet visible={sheetVisible} user={user} onClose={() => setSheetVisible(false)} onAction={openSetting} onAuth={() => { setSheetVisible(false); setAuthVisible(true); }} /><AuthModal visible={authVisible} onClose={() => setAuthVisible(false)} onAuthenticated={authenticate} /><SettingsModal visible={Boolean(settingMode)} mode={settingMode || ''} user={user} readerMode={readerMode} onClose={() => setSettingMode(null)} onSaveProfile={saveProfile} onUploadAvatar={uploadAvatar} onChangePassword={changePassword} onReaderMode={chooseReaderMode} /></SafeAreaView>;
}

const styles = StyleSheet.create({
  app: { flex: 1, backgroundColor: COLORS.background }, homeList: { paddingBottom: 105, paddingHorizontal: 16 }, gridRow: { justifyContent: 'space-between' }, header: { paddingTop: 12, paddingBottom: 24, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, logo: { color: COLORS.textPrimary, fontSize: 24, fontWeight: '900' }, logoAccent: { color: COLORS.primary }, greeting: { color: COLORS.textMuted, fontSize: 11, marginTop: 2 }, headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 }, headerIcon: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.surfaceLight }, avatar: { overflow: 'hidden', alignItems: 'center', justifyContent: 'center', backgroundColor: '#3B2520' }, avatarImage: { width: '100%', height: '100%' }, avatarText: { color: COLORS.primary, fontWeight: '900' }, headerAvatar: { width: 37, height: 37, borderRadius: 19, borderWidth: 1.5, borderColor: COLORS.primary }, headerAvatarText: { fontSize: 10 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end' }, eyebrow: { color: COLORS.primary, fontSize: 10, letterSpacing: 1.1, fontWeight: '800', marginBottom: 4 }, heading: { color: COLORS.textPrimary, fontSize: 22, fontWeight: '800' }, seeAll: { color: COLORS.primary, fontSize: 12, fontWeight: '700' }, quickList: { paddingVertical: 16, gap: 13 }, quickItem: { width: 62, alignItems: 'center' }, quickRing: { height: 54, width: 54, borderRadius: 27, padding: 2, borderWidth: 2, borderColor: COLORS.primary }, quickCover: { width: '100%', height: '100%', borderRadius: 26 }, quickName: { color: COLORS.textSecondary, fontSize: 10, marginTop: 5, width: 67, textAlign: 'center' }, latestHeader: { marginTop: 5, marginBottom: 13 },
  storyCard: { width: '48.2%', marginBottom: 19 }, coverWrap: { height: 226, borderRadius: 14, overflow: 'hidden', backgroundColor: COLORS.surfaceLight }, cover: { width: '100%', height: '100%' }, coverShade: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,.19)' }, metrics: { position: 'absolute', top: 8, width: '100%', paddingHorizontal: 8, flexDirection: 'row', justifyContent: 'space-between' }, metric: { fontSize: 10, color: '#FFF', fontWeight: '800', backgroundColor: 'rgba(12,12,14,.65)', paddingVertical: 3, paddingHorizontal: 5, borderRadius: 6, overflow: 'hidden' }, tagRow: { position: 'absolute', left: 7, right: 7, bottom: 8, flexDirection: 'row', gap: 4 }, tag: { backgroundColor: 'rgba(18,18,20,.83)', paddingHorizontal: 6, paddingVertical: 4, borderRadius: 7 }, tagText: { color: '#FFF', fontSize: 9, fontWeight: '700' }, storyTitle: { color: COLORS.textPrimary, fontWeight: '700', fontSize: 13, marginTop: 8, lineHeight: 17, minHeight: 34 }, storyAuthor: { color: COLORS.textMuted, fontSize: 11, marginTop: 3 },
  pageContent: { paddingHorizontal: 18, paddingTop: 22, paddingBottom: 108 }, pageTitle: { color: COLORS.textPrimary, fontSize: 27, fontWeight: '900' }, pageIntro: { color: COLORS.textSecondary, fontSize: 13, marginTop: 7, lineHeight: 20 }, categorySection: { marginTop: 20 }, letter: { color: COLORS.primary, fontSize: 20, fontWeight: '900', marginBottom: 8 }, categoryCard: { minHeight: 58, paddingHorizontal: 13, marginBottom: 8, borderRadius: 12, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border, flexDirection: 'row', alignItems: 'center' }, categoryNumber: { color: COLORS.textMuted, fontSize: 11, fontWeight: '800', width: 35 }, categoryName: { color: COLORS.textPrimary, fontSize: 14, fontWeight: '700', flex: 1 }, categoryCount: { color: COLORS.textSecondary, fontSize: 11 }, chevron: { color: COLORS.primary, fontSize: 23, marginLeft: 10 },
  searchPage: { flex: 1, padding: 18 }, searchTop: { flexDirection: 'row', alignItems: 'center', marginBottom: 18 }, searchBack: { width: 33 }, searchTitle: { color: COLORS.textPrimary, fontSize: 21, fontWeight: '900' }, backText: { color: COLORS.primary, fontSize: 30, lineHeight: 24 }, searchBox: { height: 49, flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.surfaceLight, borderRadius: 13, borderWidth: 1, borderColor: COLORS.border, paddingHorizontal: 12 }, searchGlyph: { color: COLORS.textSecondary, fontSize: 22, marginRight: 7 }, searchInput: { flex: 1, color: COLORS.textPrimary, fontSize: 14, height: '100%' }, clearSearch: { color: COLORS.textSecondary, fontSize: 22, width: 21, textAlign: 'right' }, searchState: { marginTop: 30 }, searchResults: { paddingTop: 13, paddingBottom: 25 }, searchResult: { minHeight: 91, paddingVertical: 9, borderBottomWidth: 1, borderColor: COLORS.border, flexDirection: 'row', alignItems: 'center' }, searchCover: { width: 48, height: 67, borderRadius: 8, backgroundColor: COLORS.surfaceLight }, searchCopy: { flex: 1, marginLeft: 11 }, searchStoryTitle: { color: COLORS.textPrimary, fontSize: 14, fontWeight: '800', lineHeight: 18 }, searchChapter: { color: COLORS.primary, fontSize: 10, marginTop: 6 },
  pills: { flexDirection: 'row', gap: 8, marginTop: 20, marginBottom: 8 }, pill: { paddingHorizontal: 12, paddingVertical: 9, backgroundColor: COLORS.surfaceLight, borderRadius: 10 }, pillActive: { backgroundColor: COLORS.primary }, pillText: { color: COLORS.textSecondary, fontSize: 11, fontWeight: '700' }, pillTextActive: { color: '#FFF' }, libraryItem: { minHeight: 85, borderBottomWidth: 1, borderColor: COLORS.border, paddingVertical: 10, flexDirection: 'row', alignItems: 'center' }, libraryCover: { width: 46, height: 64, borderRadius: 8, backgroundColor: COLORS.surfaceLight }, libraryInfo: { flex: 1, marginLeft: 11 }, libraryStory: { color: COLORS.textPrimary, fontSize: 13, fontWeight: '700', marginBottom: 4 }, progressTrack: { height: 4, borderRadius: 4, backgroundColor: COLORS.surfaceLight, marginTop: 10, overflow: 'hidden' }, progressFill: { height: '100%', backgroundColor: COLORS.primary, borderRadius: 4 },
  rankItem: { minHeight: 87, flexDirection: 'row', alignItems: 'center', gap: 10, borderBottomWidth: 1, borderColor: COLORS.border }, rankNumber: { width: 26, color: COLORS.textMuted, fontWeight: '900', fontSize: 14 }, rankNumberHot: { color: COLORS.primary }, rankCover: { width: 42, height: 60, borderRadius: 7 }, rankInfo: { flex: 1 }, rankTitle: { color: COLORS.textPrimary, fontWeight: '700', fontSize: 13 }, rankViews: { color: COLORS.primary, fontSize: 10, marginTop: 5 },
  guestPage: { flex: 1, padding: 23, justifyContent: 'center' }, guestButton: { alignSelf: 'flex-start', marginTop: 20, paddingHorizontal: 17, height: 48, borderRadius: 12, justifyContent: 'center', backgroundColor: COLORS.primary }, profileHero: { alignItems: 'center', marginTop: 10, paddingVertical: 19, borderBottomWidth: 1, borderColor: COLORS.border }, profileAvatar: { width: 86, height: 86, borderRadius: 43, borderWidth: 3, borderColor: COLORS.primary }, profileAvatarText: { fontSize: 23 }, profileName: { color: COLORS.textPrimary, fontSize: 20, fontWeight: '800', marginTop: 12 }, profileEmail: { color: COLORS.textSecondary, fontSize: 12, marginTop: 4 }, profileButton: { backgroundColor: COLORS.surfaceLight, paddingVertical: 10, paddingHorizontal: 14, borderRadius: 10, marginTop: 16 }, profileButtonText: { color: COLORS.textPrimary, fontSize: 12, fontWeight: '700' }, subheading: { color: COLORS.textPrimary, fontSize: 17, fontWeight: '800', marginTop: 25, marginBottom: 11 }, statRow: { flexDirection: 'row', backgroundColor: COLORS.surface, borderRadius: 15, paddingVertical: 16 }, stat: { flex: 1, alignItems: 'center' }, statValue: { color: COLORS.primary, fontSize: 20, fontWeight: '900' }, statLabel: { color: COLORS.textSecondary, fontSize: 10, marginTop: 5 },
  detail: { flex: 1 }, detailContent: { padding: 18, paddingBottom: 42 }, backButton: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 }, backLabel: { color: COLORS.textSecondary, fontSize: 13, fontWeight: '700', marginLeft: 5 }, detailHero: { flexDirection: 'row' }, detailCover: { width: 123, height: 180, borderRadius: 14, backgroundColor: COLORS.surfaceLight }, detailInfo: { flex: 1, paddingLeft: 14 }, detailTitle: { color: COLORS.textPrimary, fontSize: 20, lineHeight: 26, fontWeight: '900' }, detailAuthor: { color: COLORS.textSecondary, fontSize: 12, marginTop: 8 }, detailStats: { color: COLORS.primary, fontSize: 11, marginTop: 9, fontWeight: '700' }, detailTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginTop: 11 }, actionRow: { flexDirection: 'row', gap: 8, marginTop: 21 }, readButton: { flex: 1, height: 48, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.primary }, readButtonText: { color: '#FFF', fontWeight: '900', fontSize: 13 }, secondaryButton: { justifyContent: 'center', paddingHorizontal: 11, borderRadius: 12, backgroundColor: COLORS.surfaceLight, borderWidth: 1, borderColor: COLORS.border }, secondaryButtonText: { color: COLORS.textPrimary, fontSize: 11, fontWeight: '700' }, iconAction: { width: 48, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.surfaceLight, borderWidth: 1, borderColor: COLORS.border }, activeButton: { borderColor: COLORS.primary, backgroundColor: COLORS.primarySoft }, description: { color: COLORS.textSecondary, fontSize: 13, lineHeight: 21 }, chapter: { minHeight: 61, paddingHorizontal: 14, borderRadius: 11, marginBottom: 8, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, chapterTitle: { color: COLORS.textPrimary, fontSize: 13, fontWeight: '700' }, chapterDate: { color: COLORS.textMuted, fontSize: 10, marginTop: 4 }, commentForm: { flexDirection: 'row', gap: 8, alignItems: 'flex-end' }, commentInput: { flex: 1, minHeight: 48, maxHeight: 110, color: COLORS.textPrimary, padding: 11, borderRadius: 11, backgroundColor: COLORS.surfaceLight, borderWidth: 1, borderColor: COLORS.border, textAlignVertical: 'top' }, commentSend: { height: 48, paddingHorizontal: 14, justifyContent: 'center', borderRadius: 11, backgroundColor: COLORS.primary }, commentSendText: { color: '#FFF', fontWeight: '800' }, comment: { flexDirection: 'row', marginTop: 15 }, commentAvatar: { width: 35, height: 35, borderRadius: 18 }, commentBody: { flex: 1, marginLeft: 9 }, commentUser: { color: COLORS.textPrimary, fontSize: 12, fontWeight: '800' }, commentContent: { color: COLORS.textSecondary, fontSize: 12, lineHeight: 18, marginTop: 3 }, commentDate: { color: COLORS.textMuted, fontSize: 10, marginTop: 5 },
  reader: { flex: 1, backgroundColor: '#080809' }, readerHeader: { position: 'absolute', top: 0, left: 0, right: 0, zIndex: 2, height: 75, paddingTop: 22, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(18,18,20,.95)' }, readerBack: { width: 34 }, readerHeaderText: { color: '#FFF', fontSize: 28 }, readerHeading: { flex: 1, alignItems: 'center' }, readerTitle: { color: '#FFF', fontWeight: '800', fontSize: 13, maxWidth: 210 }, readerChapter: { color: COLORS.textSecondary, fontSize: 10, marginTop: 2 }, readerPages: { paddingBottom: 56 }, readerPage: { width: '100%', position: 'relative' }, readerImage: { width: '100%', height: 560, backgroundColor: COLORS.surfaceLight }, readerLoading: { marginTop: 160 }, readerEmpty: { color: COLORS.textSecondary, textAlign: 'center', marginTop: 160, paddingHorizontal: 30 }, readerPageNumber: { position: 'absolute', bottom: 8, right: 10, backgroundColor: 'rgba(0,0,0,.6)', borderRadius: 5, overflow: 'hidden', color: '#DDD', paddingHorizontal: 7, paddingVertical: 3, fontSize: 10 }, readerFooter: { position: 'absolute', bottom: 0, left: 0, right: 0, minHeight: 54, backgroundColor: 'rgba(18,18,20,.95)', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', paddingHorizontal: 7 }, readerFooterText: { color: '#FFF', fontSize: 10, fontWeight: '700' }, readerDisabled: { opacity: .35 },
  sheetOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,.6)' }, chapterSheet: { maxHeight: '65%', padding: 20, paddingBottom: 30, borderTopLeftRadius: 25, borderTopRightRadius: 25, backgroundColor: COLORS.surface }, sheetTitle: { color: COLORS.textPrimary, fontSize: 18, fontWeight: '900', marginBottom: 13 }, sheetChapter: { paddingVertical: 14, borderBottomWidth: 1, borderColor: COLORS.border }, sheetChapterActive: { paddingHorizontal: 9, borderRadius: 9, backgroundColor: COLORS.primarySoft }, sheetChapterText: { color: COLORS.textPrimary, fontSize: 13 },
  modalOverlay: { flex: 1, justifyContent: 'center', padding: 20, backgroundColor: 'rgba(0,0,0,.67)' }, settingsCard: { borderRadius: 22, padding: 20, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border }, settingsTitle: { color: COLORS.textPrimary, fontSize: 20, fontWeight: '900', marginBottom: 13 }, modalDescription: { color: COLORS.textSecondary, fontSize: 13, lineHeight: 20 }, settingChoice: { padding: 14, borderRadius: 11, marginTop: 10, backgroundColor: COLORS.surfaceLight }, settingChoiceActive: { borderWidth: 1, borderColor: COLORS.primary, backgroundColor: COLORS.primarySoft }, settingChoiceText: { color: COLORS.textPrimary, fontWeight: '700', fontSize: 13 }, avatarPicker: { minHeight: 76, padding: 9, borderRadius: 12, borderWidth: 1, borderColor: COLORS.border, backgroundColor: COLORS.surfaceLight, flexDirection: 'row', alignItems: 'center', gap: 11 }, avatarPickerImage: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#3B2520' }, avatarPickerTitle: { color: COLORS.textPrimary, fontSize: 13, fontWeight: '800' }, avatarPickerHint: { color: COLORS.textMuted, fontSize: 10, marginTop: 4 }, modalInput: { height: 48, marginTop: 9, paddingHorizontal: 12, borderRadius: 10, borderWidth: 1, borderColor: COLORS.border, color: COLORS.textPrimary, backgroundColor: COLORS.surfaceLight }, modalSave: { height: 48, marginTop: 16, borderRadius: 11, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' }, modalSaveText: { color: '#FFF', fontWeight: '900' }, modalCancel: { alignSelf: 'center', padding: 10, marginTop: 7 }, modalCancelText: { color: COLORS.textSecondary, fontSize: 12, fontWeight: '700' },
  tabBar: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 78, backgroundColor: 'rgba(26,26,30,.98)', borderTopLeftRadius: 22, borderTopRightRadius: 22, borderTopWidth: 1, borderColor: COLORS.border, flexDirection: 'row', justifyContent: 'space-around', paddingHorizontal: 5 }, tab: { width: '20%', alignItems: 'center', paddingTop: 12 }, tabIcon: { color: COLORS.textMuted, fontSize: 21, lineHeight: 22 }, tabActive: { color: COLORS.primary }, tabLabel: { color: COLORS.textMuted, fontSize: 9, marginTop: 3, fontWeight: '600' }, tabLabelActive: { color: COLORS.primary }, centerTabSlot: { paddingTop: 0 }, centerButton: { position: 'absolute', top: -24, width: 57, height: 57, borderRadius: 29, backgroundColor: COLORS.primary, justifyContent: 'center', alignItems: 'center', borderWidth: 5, borderColor: COLORS.background, elevation: 8 }, centerButtonActive: { backgroundColor: '#FF845F' }, centerIcon: { color: '#FFF', fontSize: 26, fontWeight: '900' }, centerLabel: { position: 'absolute', top: 43 },
  empty: { alignItems: 'center', justifyContent: 'center', paddingVertical: 32 }, emptyText: { color: COLORS.textSecondary, textAlign: 'center', fontSize: 13, lineHeight: 20, marginTop: 10 }, errorText: { color: '#FF9A80', textAlign: 'center', fontSize: 12, marginTop: 12 }, disabled: { opacity: .55 },
});
